apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: grafana
      version: 0.67.x
      sourceRef:
        kind: HelmRepository
        name: loki-distributed
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    serviceMonitor:
      enabled: true
      targetLabels:
    loki:
      containerSecurityContext:
        readOnlyRootFilesystem: false
      
      config: |
        auth_enabled: false
        server:
          http_listen_port: 3100
        distributor:
          ring:
            kvstore:
              store: memberlist
        memberlist:
          join_members:
            - {{ include "loki.fullname" . }}-memberlist
        ingester:
          lifecycler:
            ring:
              kvstore:
                store: memberlist
              replication_factor: 1
          chunk_idle_period: 30m
          chunk_block_size: 262144
          chunk_encoding: snappy
          chunk_retain_period: 1m
          max_transfer_retries: 0
          wal:
            dir: /var/loki/wal
        limits_config:
          enforce_metric_name: false
          reject_old_samples: true
          reject_old_samples_max_age: 168h
          max_cache_freshness_per_query: 10m
      
        schema_config:
          configs:
          - from: 2020-09-07
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: loki_index_
              period: 24h

        storage_config:
          boltdb_shipper:
            shared_store: filesystem
            active_index_directory: /var/loki/index
            cache_location: /var/loki/cache
            cache_ttl: 168h
            index_gateway_client:
              server_address: dns:///{{ include "loki.indexGatewayFullname" . }}:9095

        chunk_store_config:
          max_look_back_period: 0s
        table_manager:
          retention_deletes_enabled: false
          retention_period: 0s
        query_range:
          align_queries_with_step: true
          max_retries: 5
          split_queries_by_interval: 15m
          cache_results: true
          results_cache:
            cache:
              enable_fifocache: true
              fifocache:
                max_size_items: 1024
                validity: 24h
        frontend_worker:
          frontend_address: {{ include "loki.queryFrontendFullname" . }}:9095
        frontend:
          log_queries_longer_than: 5s
          compress_responses: true
          tail_proxy_url: http://{{ include "loki.querierFullname" . }}:3100
        compactor:
          working_directory: /var/loki/compactor
          shared_store: filesystem
        ruler:
          storage:
            type: local
            local:
              directory: /etc/loki/rules
          ring:
            kvstore:
              store: memberlist
          rule_path: /tmp/loki/scratch

    gateway:
      serverSnippet: "client_max_body_size 100M;"

    indexGateway:
      enabled: true

      persistence:
        enabled: true

    querier:
      replicas: 1
      extraVolumes:
        - name: bolt-db
          emptyDir: {}
      extraVolumeMounts:
        - name: bolt-db
          mountPath: /var/loki